default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "yuriy") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: serviceflow_development

test:
  <<: *default
  database: serviceflow_test

production:
  <<: *default
  database: serviceflow_production
  username: <%= ENV.fetch("DB_USERNAME") { "serviceflow" } %>
  password: <%= ENV["SERVICEFLOW_DATABASE_PASSWORD"] %>
